### ISSUE TITLE
Query sample no longer works with 3.x

### ISSUE THREAD

**Issue by andrejpk** [Azure/azure-kusto-java#219]
**Describe the bug**
The `HttpClientProperties` reference in the samples/../Query.java example does not compile with the version of the kusto client in the library (3.x).

With the 3.x changes, HttpClientProperties reference is invalid:

```
[ERROR] /..../azure-kusto-java/samples/src/main/java/Query.java:[6,38] cannot find symbol
[ERROR]   symbol:   class HttpClientProperties
[ERROR]   location: package com.microsoft.azure.kusto.data
[ERROR] /..../azure-kusto-java/samples/src/main/java/Query.java:[24,13] cannot find symbol
[ERROR]   symbol:   class HttpClientProperties
[ERROR]   location: class Query
[ERROR] /..../azure-kusto-java/samples/src/main/java/Query.java:[24,47] cannot find symbol
[ERROR]   symbol:   variable HttpClientProperties
[ERROR]   location: class Query
```

**To Reproduce**
- Clone repo
- Follow samples/README.md instruction to run the Query example

**Expected behavior**
Should run as documented

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by yihezkel** [comment]
I can't reproduce this, which makes sense to me, since as of v3.0.0, `com.microsoft.azure.kusto.data.HttpClientProperties` indeed didn't yet exist, but I don't see a reference to it in `Query.java` - see https://github.com/Azure/azure-kusto-java/blob/v3.0.0/samples/src/main/java/Query.java

The `HttpClientProperties` file, the `samples` project's `pom.xml` including the dependency on `kusto.data`, and the reference to it in `Query.java` all appeared in the repo after v3.0.0 (not yet released).

Would you please try deleting the contents of your local repo, making sure you have v3.0.0 of the `samples` module, and trying again?
