### ISSUE TITLE
The current version of the jackson-databind dependency has a security vulnerability

### ISSUE THREAD

**Issue by melmerp** [Azure/azure-kusto-java#238]
**Describe the bug**
The latest (3.1.0) version of azure-kusto-java uses jackson-databind version 2.12.5. However, this version of jackson-databind has a security vulnerability.

Is it possible to upgrade to using 2.13.2.1 or 2.13.2.2 (the two latest released jackson-databind libraries)?

See: 
https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518

**To Reproduce**
N/A

**Expected behavior**
Using a secure version of jackson-databind.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.3

**Additional context**
N/A

**Comment by yihezkel** [comment]
Because Jackson is such a common dependency, we provide a wide range of versions (`[2.11.0,2.13.0]`) that work with this SDK. This range includes 2.12.6.1 that I see (https://github.com/FasterXML/jackson-databind/issues/2816) has the CVE fix.

**Comment by yihezkel** [comment]
I confirmed that we are not affected by this vulnerability.

Per https://github.com/FasterXML/jackson-databind/issues/2816 and the actual fix (https://github.com/FasterXML/jackson-databind/pull/3416/files), this only affects deserializing without type - `ObjectMapper.readValue(myObj, Object.class)`

Our code only uses Jackson to serialize data - `ObjectMapper.writeValue()`, with the exception of the QuickStart, which deserializes **with** type:
`new ObjectMapper().readValue(configFile, HashMap.class);`

Our code is thus not vulnerable, our pom provides a range that includes versions with the fix, and we intentionally don't want to increase the low-end of the range because of how common the jackson dependencies are particularly in environments where our SDK is included which can lead to challenging version conflicts for our users (e.g. Databricks).
