### ISSUE TITLE
Setting timeout via the code does not stop the query 

### ISSUE THREAD

**Issue by ashwanikumar04** [Azure/azure-kusto-java#336]
**Describe the bug**
I am creating `ClientRequestProperties` as
```
  ClientRequestProperties adxQueryRequestProperties = new ClientRequestProperties();
        adxQueryRequestProperties.setClientRequestId("random id");
        adxQueryRequestProperties.setTimeoutInMilliSec(2000);
       
```

and then passing this to execute the command.
```
client.execute(connection, query, adxQueryRequestProperties)
```
Even though the query take more than 10 second to run, the above code does not through timeout exception. Am I missing any thing. 

**To Reproduce**
Same as above.

**Expected behavior**
The code should throw exception in case the query take more time than the specified time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: java 11

**Additional context**

**Comment by yihezkel** [comment]
Hi @ashwanikumar04,

I couldn't reproduce your issue:
<img width="979" alt="image" src="https://github.com/Azure/azure-kusto-java/assets/30245027/7513625a-7057-4086-8cd7-c8fe2476f82e">

Note that the SDK allows for a 30s buffer to account for client-server connection timing.

In our backend for my test, we see the 8s timeout + the 30s buffer between receiving the  request and the backend timing out:
<img width="535" alt="image" src="https://github.com/Azure/azure-kusto-java/assets/30245027/7ec56032-b819-4e5d-a178-5a7cd1424ae2">

It seems you aren't taking into account these 30s, since your query took 10s and your timeout was set to 2s.

If you still see this issue after accounting for those 30s, would you please provide a `ClientRequestId` and approximate UTC time of execution?

**Comment by ashwanikumar04** [comment]
Hello Yihezkel:

Thanks for the reply.

This makes sense.
In this case, is there any way we can limit "30s buffer to account for
client-server connection timing" to something less?


Thanks,
*Ashwani Kumar*

**Comment by yihezkel** [comment]
Thanks again @ashwanikumar04 for bringing this to our attention!

As you probably saw, I've linked this issue to a PR (#339) which should resolve the issue for you in our next release.

Another point to keep in mind is that the service only enforces a value of `ClientRequestProperties.servertimeout` between 1 minute and 1 hour, so your example of 2 seconds would in effect be treated as 1 minute. We'll make that clearer.
